### ISSUE TITLE
where not only applies to go statements

### ISSUE THREAD

**Issue by Shinji-IkariG** [vesoft-inc/nebula-docs#102]
where also applies to lookup on syntax

![image](https://user-images.githubusercontent.com/58841610/85094910-85b3b280-b222-11ea-80ce-231534bca9e8.png)

**Comment by Amber1990Zhang** [comment]
good point.
Currently, the `WHERE` statement applies to the `GO` and `LOOKUP` statement. Note some `WHERE` filter conditions are not supported in the `LOOKUP` statement. Refer to the LOOKUP DOC for details.
Will this make sense?
