### ISSUE TITLE
List and add detail explanation of nebula graph metrics

### ISSUE THREAD

**Issue by kqzh** [vesoft-inc/nebula-docs#1128]
## Change Request

1. Describe what you find is inappropriate or missing in the existing docs.
In https://docs.nebula-graph.io/3.0.0/6.monitor-and-metrics/1.query-performance-metrics/, it doesn't show what metrics are provided by nebula and each metric's explanation now.

3. Describe your suggestion or addition.
 I think metics are helpful for monitoring. Can we add each nebula metric and its explanation like https://docs.nebula-graph.io/3.0.0/nebula-dashboard-ent/7.monitor-parameter/

4. Provide some reference materials (documents, websites, etc) if you could.
N/A

**Comment by abby-cyber** [comment]
https://docs.nebula-graph.io/3.1.0/6.monitor-and-metrics/1.query-performance-metrics/ done
