### ISSUE TITLE
Listing clients maintained under non vesoft-inc github org & others

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs#1202]
Maybe exposed under: https://docs.nebula-graph.io/3.0.1/14.client/1.nebula-client/

--------------------
ref: https://github.com/nebula-contrib/

- https://github.com/nebula-contrib/nebula-jdbc
- https://github.com/nebula-contrib/nebula-php
- https://github.com/nebula-contrib/nebula-net
- https://github.com/nebula-contrib/nebula-node
- https://github.com/zhihu/norm

**Comment by whitewum** [comment]
since they're not actively maintained, and so QA is guaranteed. I can't list them in the manual. But I can ref them with a caution note.

**Comment by abby-cyber** [comment]
done
