### ISSUE TITLE
Highlight in balance related chapters on how to enable this feature

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs#1358]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

User queried this on how the feature is still not usable in 3.1

2. Describe your suggestion or addition.

We could add notices to make them aware of how it's not turned on by default and where to switch it on.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by cooper-lzy** [comment]
The `Balance Data` feature is supported in the enterprise edition.

**Comment by wey-gu** [comment]
For whom found this issue being confused, `enable_experimental_feature` is the flag to enable `BALANCE DATA` in Nebula Graph version of 3.1.0 +
