### ISSUE TITLE
Recommended to add a description in BALANCE DATA

### ISSUE THREAD

**Issue by MuYiYong** [vesoft-inc/nebula-docs#1718]
# Error Report

**This repository is ONLY used to solve issues related to DOCS.**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?
https://docs.nebula-graph.com.cn/3.2.0/synchronization-and-migration/2.balance-syntax/

2. How would you like to improve it?
It is recommended to add a description in BALANCE DATA: This feature belongs to the Enterprise Edition

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated NebulaGraph to most recent version
- [x] I included all the necessary information above

**Comment by whitewum** [comment]
![image](https://user-images.githubusercontent.com/50101159/198935999-fce649c7-16d2-4ce1-b162-ba20b0a9cd13.png)

Please look carefully. Do not skip the first line.

**Comment by whitewum** [comment]
Besides, balance data is for enterprise usage only.
So check the 3.1.0 not 3.2.0 as you're the product designer.
