### ISSUE TITLE
Docker Compose should be exposed/highlighted as the quick start

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs#2200]
see: https://github.com/vesoft-inc/nebula/issues/5659

The first-time user trying NebulaGraph with a server may go to the binary deployment, but in their journey, the add-hosts could block them, we should point them that docker-compose is the easiest way.

**Comment by abby-cyber** [comment]
Here you go https://github.com/vesoft-inc/nebula-docs/pull/2209
