### ISSUE TITLE
Please make it clear that TTL column should build upon a timestamp  column and usually it's set to the insertion time of the data

### ISSUE THREAD

**Issue by wenhaocs** [vesoft-inc/nebula-docs#2264]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by cooper-lzy** [comment]
It can also be an int type, not just a timestamp type, and in the example, we provide user with the example of inserting a current timestamp and setting a future date to expire.
![image](https://github.com/vesoft-inc/nebula-docs/assets/78672629/c23c11eb-f6b1-419a-bcb6-8d527a734854)

![image](https://github.com/vesoft-inc/nebula-docs/assets/78672629/3eb7f54e-dffa-49f4-b413-98d3db7fc61a)

**Comment by wenhaocs** [comment]
It's hidden in the example, and no summary. Please add a summary.

**Comment by abby-cyber** [comment]
> It's hidden in the example, and no summary. Don't expect users will read example and then try to figure it by themselves. Please add a summary. Remember: `Coach the user, not let user figure out by themselves`

Agree!

**Comment by abby-cyber** [comment]
> > It's hidden in the example, and no summary. Don't expect users will read example and then try to figure it by themselves. Please add a summary. Remember: `Coach the user, not let user figure out by themselves`
> 
> Agree!

https://github.com/vesoft-inc/nebula-docs/pull/2265/commits/bf153113035d73e7db255187bd853a4dc81be7ad updated
