### ISSUE TITLE
Statements with special characters need to be escaped

### ISSUE THREAD

**Issue by liangliangc** [vesoft-inc/nebula-docs#2405]
### 环境
库：192.168.8.131:9669
空间：test_1
版本：3.6.0-ent
### 一、个别特殊字符 加了反引号 仍需转译
真实的Tag和属性 是一个\ 实际语句需要多加一个译
```
INSERT VERTEX `q12^%$~e34\\` (`nam^%$~e\\`) VALUES "123":("123")
```
![image](https://github.com/vesoft-inc/nebula-docs/assets/102048716/bfcb773e-5504-495f-86e6-c44b0916bfe8)

### 二、UPDATE语句 属性名为INT类型 需加反引号
```
UPDATE VERTEX ON tttttttesttttttttt "0.15player108" SET `6` = 1
```
![image](https://github.com/vesoft-inc/nebula-docs/assets/102048716/ebc1b015-580c-4286-bc43-26c4060db3c3)
![image](https://github.com/vesoft-inc/nebula-docs/assets/102048716/683e9348-11f5-4d0e-b9d1-43b3dacd5563)

**Comment by abby-cyber** [comment]
1. 看起来像第一个反斜杠（\）是转义符。
2. 属性的命名规则和tag相同。即如果需要使用特殊字符、保留关键字或者以数字开头，请使用反引号（`）包围整个名称。
所以这里的6打引号符合预期。
<img width="1068" alt="image" src="https://github.com/vesoft-inc/nebula-docs/assets/78209557/7c20dc24-2690-425e-8f39-1c6c1740cc58">

```
(root@nebula) [basketballplayer]> insert vertex test1 (6) values "abby1": (1)
[ERROR (-1004)]: SyntaxError: syntax error near `6) value'

Thu, 28 Dec 2023 13:41:11 CST

(root@nebula) [basketballplayer]> insert vertex test1 (`6`) values "abby1": (1)
Execution succeeded (time spent 2764/3157 us)

(root@nebula) [basketballplayer]> update vertex on test1 "abby1" set `6`=2
Execution succeeded (time spent 1573/1990 us)
```

**Comment by abby-cyber** [comment]
https://github.com/vesoft-inc/nebula-docs/pull/2406/files
