### ISSUE TITLE
The chinese descriptions of some statistical items related to the execution of certain operators are incorrect.

### ISSUE THREAD

**Issue by AntiTopQuark** [vesoft-inc/nebula-docs#2481]
# Error Report

**This repository is ONLY used to solve issues related to DOCS.**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?
https://docs.nebula-graph.com.cn/3.6.0/6.monitor-and-metrics/1.query-performance-metrics/

2. How would you like to improve it?
The true interpretation pertains to the count of executions. This is consistently defined as the number of executions across the codebase and English documentation. Conversely, the Chinese translation inaccurately denotes it as 'execution time', deviating from the factual context.

![image](https://github.com/vesoft-inc/nebula-docs/assets/32798045/33fea6e3-f120-40b6-b68c-41da9506f474)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated NebulaGraph to most recent version
- [x] I included all the necessary information above

**Comment by cooper-lzy** [comment]
Thanks for your feedback, the error has been fixed.
