### ISSUE TITLE
NebulaGraph Importer page failed

### ISSUE THREAD

**Issue by BoyuanGao** [vesoft-inc/nebula-docs#2568]
https://docs.nebula-graph.com.cn/3.8.0/nebula-importer/use-importer/

![image](https://github.com/vesoft-inc/nebula-docs/assets/141694963/85756564-6814-4cfa-a589-e7cbc1e23f67)

**Comment by abby-cyber** [comment]
See the updated page at https://docs.nebula-graph.com.cn/3.8.0/import-export/use-importer/ .

**Comment by BoyuanGao** [comment]
worked, thanks @abby-cyber
