### ISSUE TITLE
dont quite understand what does `alter user` do

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula-docs#39]
Based on the doc, I don't quite understand what does `alter user` do and the difference between `change password` && `alter user`.

![image](https://user-images.githubusercontent.com/51590253/80339801-ff1dcd00-8891-11ea-9068-3929e88406b2.png)

**Comment by Amber1990Zhang** [comment]
alter user用来改用户密码。alter无需密码校验。
@bright-starry-sky 大神帮忙解释一下。

**Comment by bright-starry-sky** [comment]
For 'alter user' statement . only the root user has executive privilege,  and can change any user's password. For example, when the user forgets the password, the root need to change the password for the user.
For 'change password' statement. Anyone can change their password, but must know their old password. If you forget your password, you need root to change it through statement  'alter user'.
