### ISSUE TITLE
Add manual about `go from <vid> over *`

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula-docs#45]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by Amber1990Zhang** [comment]
Do you mean this?
![image](https://user-images.githubusercontent.com/42762957/81460769-0b7f1f80-91da-11ea-8962-0f5dd33c636a.png)
