### ISSUE TITLE
Docs search with site:google.com doesn't work well as native search in docs-cn

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs#539]
## Change Request

1. Describe what you find is inappropriate or missing in the existing docs.

It seems searching now in docs-en doesn't work well, it indexed things:
- contents other than only docs.nebula-graph.io
- contents other than currently selected version

2. Describe your suggestion or addition.
Could we use native search as it is in docs-cn?

3. Provide some reference materials (documents, websites, etc) if you could.
as above.

**Comment by whitewum** [comment]
Noticed. We are trying several other searching ways in this repo.

You can download the pdf and search as a walkaround.

**Comment by wey-gu** [comment]
> Noticed. We are trying several other searching ways in this repo.
> 
> You can download the pdf and search as a walkaround.

Thanks! Good to know, and got it :) Dr. Wu.
