### ISSUE TITLE
BZip2 is required for compiling Nebula Graph

### ISSUE THREAD

**Issue by JaySon-Huang** [vesoft-inc/nebula-docs#567]
# Error Report

**This repository is ONLY used to solve issues related to DOCS.**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://docs.nebula-graph.io/master/4.deployment-and-installation/1.resource-preparations/#software_requirements_for_compiling_nebula_graph

2. How would you like to improve it?

BZip2 is required for compiling Nebula Graph[1], but it is not listed in the software requirements document

* [1] https://github.com/vesoft-inc/nebula-common/blob/37976d7cdf02b6dccd1d8e0ab29301e4b06e1ebb/cmake/nebula/ThirdPartyConfig.cmake#L81
```
>  cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" -DENABLE_BUILD_STORAGE=ON -Wno-dev .. 
>>>> Options of Nebula Graph <<<<
...
>>>> Configuring third party for 'Nebula Graph' <<<<
-- Downloading prebuilt third party automatically...
-- cxx_cmd: /usr/local/bin/g++ -D_GLIBCXX_USE_CXX11_ABI=1
Downloading vesoft-third-party-2.0-x86_64-libc-2.17-gcc-7.1.0-abi-11.sh...
Downloading vesoft-third-party-2.0-x86_64-libc-2.17-gcc-7.1.0-abi-11.sh failed
-- CMAKE_INCLUDE_PATH              : 
-- CMAKE_LIBRARY_PATH              : 
-- CMAKE_PROGRAM_PATH              : 
-- GLIBC_VERSION                   : 2.17

CMake Error at modules/common/cmake/FindBzip2.cmake:31 (message):
  Bzip2 doesn't exist           <-- BZip2 is required
Call Stack (most recent call first):
  modules/common/cmake/nebula/ThirdPartyConfig.cmake:81 (find_package)
  CMakeLists.txt:97 (include)
...
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated Nebula Graph to most recent version
- [x] I included all the necessary information above

**Comment by JaySon-Huang** [comment]
BZip2 is listed in the Chinese version. But the English version missed it.
https://docs.nebula-graph.com.cn/2.0.1/4.deployment-and-installation/1.resource-preparations/#_4

**Comment by wey-gu** [comment]
Dear @JaySon-Huang ,
Thanks!
Would you mind creating PR for fixing this? :)
cc @randomJoe211

**Comment by JaySon-Huang** [comment]
Sorry for the late response, I've created a PR for it. https://github.com/vesoft-inc/nebula-docs/pull/595

**Comment by wey-gu** [comment]
> Sorry for the late response, I've created a PR for it. #595

Thank you so much @JaySon-Huang :-) for your contribution to the nebula community.
