### ISSUE TITLE
The v2.0.1 version is shown as "under development" in the English website

### ISSUE THREAD

**Issue by JaySon-Huang** [vesoft-inc/nebula-docs#568]
# Error Report

**This repository is ONLY used to solve issues related to DOCS.**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://docs.nebula-graph.io/2.0.1/

2. How would you like to improve it?

Seem that the document of v2.0.1 is not set properly. There is a popup at the top of the website. I think v2.0.1 is the latest stable release version?

![image](https://user-images.githubusercontent.com/4865550/126902910-b261f0d4-dd37-4ff5-8187-845446a40e45.png)

![image](https://user-images.githubusercontent.com/4865550/126902872-c5db0783-ecd8-4a47-8ad5-8be6c08c6c0f.png)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated Nebula Graph to most recent version
- [x] I included all the necessary information above

**Comment by wey-gu** [comment]
Thank you @JaySon-Huang !
Good catch!
cc @whitewum @randomJoe211

**Comment by randomJoe211** [comment]
Thank you for pointing out this issue. It was found to be a problem with GitHub actions and now it is fixed.
