### ISSUE TITLE
What is fixed_string mean in vid_type?

### ISSUE THREAD

**Issue by aminmaghsodi** [vesoft-inc/nebula-docs#571]
Hi, In documentation of [CRUD section](https://docs.nebula-graph.io/2.0/2.quick-start/4.nebula-graph-crud/#create_and_use_a_graph_space), there is a notation that we should define `vid_type`, which could be FIXED_STRING(N). My question is about `N` parameter. What happens, when we define for example N = 10 then we put a key with length N = 2? Are those extra 8 bytes allocated and we have waste of disk usage or they will be ignored and just (2 * size of string) is allocated?

**Comment by foesa-yang** [comment]
Define N=10, if the length is less than 10, it will automatically fill in'\0'.

**Comment by aminmaghsodi** [comment]
Tahnks @foesa-yang for your time and good answer :)
