### ISSUE TITLE
英文版文档的网页左侧导航栏中 Introduction 的第二个子项应该是Data Model 而不是 Date Model

### ISSUE THREAD

**Issue by GoGoMonkey123** [vesoft-inc/nebula-docs#582]
# Error Report

**This repository is ONLY used to solve issues related to DOCS.**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

2. How would you like to improve it?

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated Nebula Graph to most recent version
- [ ] I included all the necessary information above

**Comment by wey-gu** [comment]
Thank you @GoGoMonkey123 ,
Would you mind fixing it for us? Just click the ✏️ at the corner of the docs page :-).

**Comment by GoGoMonkey123** [comment]
> Thank you @GoGoMonkey123 ,
> Would you mind fixing it for us? Just click the ✏️ at the corner of the docs page :-).

是在页面左边的导航栏上，我点那个铅笔没法改

**Comment by whitewum** [comment]
> > Thank you @GoGoMonkey123 ,
> > Would you mind fixing it for us? Just click the ✏️ at the corner of the docs page :-).
> 
> 是在页面左边的导航栏上，我点那个铅笔没法改

改 mkdocs.yml这个文件

**Comment by wey-gu** [comment]
Thank you @GoGoMonkey123 again for the kind contribution again :).
