### ISSUE TITLE
Placeholder in version 2.x edge data format description adjustment

### ISSUE THREAD

**Issue by forest-yuxl** [vesoft-inc/nebula-docs#707]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
It is not appropriate for placeholder to keep for TOSS.The TOSS implementation does not rely on this placeholder. 

2. Describe your suggestion or addition.
Drop the description of placeholder.

3. Provide some reference materials (documents, websites, etc) if you could.
<img width="789" alt="28E4CCA7-6251-4545-8B1E-276F63E1C374" src="https://user-images.githubusercontent.com/84314746/132795414-e5ba21a0-255e-468e-b05d-748d318c04d6.png">

**Comment by whitewum** [comment]
done
