### ISSUE TITLE
More best practices is supported in the documentation.

### ISSUE THREAD

**Issue by forest-yuxl** [vesoft-inc/nebula-docs#740]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
Reason:some users use session incorrectly, resulting in poor performance.We need some best practice guidance to help users avoid.

2. Describe your suggestion or addition.
Add more best practices in documentation.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by wey-gu** [comment]
Agreed! Something like a `cookbook`.

https://github.com/megaease/easegress/blob/main/doc/cookbook/README.md

**Comment by cooper-lzy** [comment]
Best practices have been added in documentation, most of them were sorted out from the blog.

https://docs.nebula-graph.io/2.6.1/8.service-tuning/practice/
