### ISSUE TITLE
Logging mechanism description

### ISSUE THREAD

**Issue by aminmaghsodi** [vesoft-inc/nebula-docs#747]
There is no any information about how we can set/change logrotate mechanism in nebula components.
There are many files with names like `nebula-storaged.nebula-3.root.log.ERROR.20210922-133823.1218` and they aren't going to delete during the time and they are just rotated. how we can change this mechanism? just with custom logrotate in OS level? How can we change the naming mechanism of logs?

**Comment by randomJoe211** [comment]
Planned in Nebula Graph v3.0. For more information, see https://github.com/vesoft-inc/nebula/issues/3066.

**Comment by wey-gu** [comment]
Log rotate was merged :)
