### ISSUE TITLE
Strongly suggest introduce same search solution in 2.5(quite usable!) to legacy versions like 2.0.1

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs#809]
As title, the old search in 2.0.1(google search based) is not that user-friendly, and users cannot even find one simple syntax with it, while there is indeed someone out there checking v2.0.1 docs(maybe their production nebula is) get tortured by this :-).

context: one of our new user complaints on:
> "Where on earth I can get to the complete manual of NGQL. I have been searching the documents from the overview till the last page I cannot find a simple way that gets me to a statement syntax. for example DROP EDGE where is that and how to get to it

Thanks!

**Comment by cooper-lzy** [comment]
Yes, I also think our search function is not working well, we need the help of developers. Before that, we can use [nGQL Cheatsheet](https://docs.nebula-graph.io/2.6.1/2.quick-start/6.cheatsheet-for-ngql/) for a quick search.
