### ISSUE TITLE
Having a single page index of all query syntax

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs#810]
Could we have a single page index cover all query syntax in one overview will be very very helpful for a new user that has little concept of all nGQL capabilities(thus they don't know which keyword to start with/search)?

Thanks!

> 
> Enas Al Kawasmi  11 minutes ago
> I found it after really struggling
> 
> Enas Al Kawasmi  10 minutes ago
> I think their should be a direct link from the get started page to the ngql index

**Comment by abby-cyber** [comment]
done
https://docs.nebula-graph.io/2.6.0/2.quick-start/6.cheatsheet-for-ngql/

thank you for your suggestion!

**Comment by wey-gu** [comment]
Thanks a lot for the amazing masterpiece!
