### ISSUE TITLE
The description of ttl in meta service need to be adjusted

### ISSUE THREAD

**Issue by forest-yuxl** [vesoft-inc/nebula-docs#918]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
Current description：
The Meta Service provides automatic data eviction and space reclamation based on TTL (time to live) options for Nebula Graph.

Suggest：
The meta service is only store TTL definition information.When the data expires and need to be cleaned up,it is handled by storage service.

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by cooper-lzy** [comment]
Modified to:
The Meta Service stores the definition of TTL (Time to Live) options which are used to control data expiration. The Storage Service takes care of the expiring and evicting processes. For more information, see TTL.
